index:
  description: "Operation is successful"
  content:
    application/json:
      schema:
        type: object
        required:
          - header
          - body
        properties:
          header:
            $ref: "../schemas.yml#/header"
          body:
            $ref: "../schemas/settings.yml#/index"
      examples:
        $ref: "../examples/settings.yml#/index/response"
