openapi: "3.1.0"
info:
  contact:
    email: "contact@passbolt.com"
  summary: "Public documentation for Passbolt's API"
  description:
    $ref: "components/descriptions.yml#/main"
  license:
    name: "AGPL-3.0"
    url: "http://www.gnu.org/licenses/agpl-3.0.html"
  termsOfService: "https://www.passbolt.com/terms"
  title: "Passbolt API Documentation"
  version: "4.9.0"

servers:
  - url: "https://passbolt.local"
    description: "API Passbolt"

paths:
  /folders.json:
    $ref: "paths/folders.yml"
  /folders/{folderId}.json:
    $ref: "paths/folder.yml"
  /groups.json:
    $ref: "paths/groups.yml"
  /groups/{groupId}.json:
    $ref: "paths/group.yml"
  /groups/{groupId}/dry-run.json:
    $ref: "paths/groupDryRun.yml"
  /resources.json:
    $ref: "paths/resources.yml"
  /resources/{resourceId}.json:
    $ref: "paths/resource.yml"
  /move/{foreignModel}/{foreignId}.json:
    $ref: "paths/move.yml"
  /resource-types.json:
    $ref: "paths/resourceTypes.yml"
  /resource-types/{resourceTypeId}.json:
    $ref: "paths/resourceType.yml"
  /roles.json:
    $ref: "paths/roles.yml"
  /users.json:
    $ref: "paths/users.yml"

tags:
  - name: "Groups"
    description:
      $ref: "components/descriptions/groups.yml#/tag"
  - name: "Move"
    description: "Move a folder or a resource across folders."
  - name: "Resources"
    description:
      $ref: "components/descriptions/resources.yml#/tag"
  - name: "Resource types"
    description:
      $ref: "components/descriptions/resourceTypes.yml#/tag"
  - name: "Roles"
    description: "Different categories of users."

components:
  securitySchemes:
    $ref: "components/securitySchemes.yml"
