openapi: "3.1.0"
info:
  contact:
    email: "contact@passbolt.com"
  summary: "Public documentation for Passbolt's API"
  description:
    $ref: "components/descriptions.yml#/main"
  license:
    name: "AGPL-3.0"
    url: "http://www.gnu.org/licenses/agpl-3.0.html"
  termsOfService: "https://www.passbolt.com/terms"
  title: "Passbolt API Documentation"
  version: "0.1.0"

servers:
  - url: "https://passbolt.com"
    description: "API Passbolt"

paths:
  /resources.json:
    $ref: "paths/resources.yml"
  /resources/{resourceId}.json:
    $ref: "paths/resource.yml"
  /move/{foreignModel}/{foreignId}.json:
    $ref: "paths/move.yml"
  /resource-types.json:
    $ref: "paths/resourceTypes.yml"
  /resource-types/{resourceTypeId}.json:
    $ref: "paths/resourceType.yml"

tags:
  - name: "Move"
    description: "Move a folder or a resource across folders."
  - name: "Resources"
    description:
      $ref: "components/descriptions/resources.yml#/tag"
  - name: "Resource types"
    description:
      $ref: "components/descriptions/resourceTypes.yml#/tag"

components:
  securitySchemes:
    $ref: "components/securitySchemes.yml"
