.build:
  stage: build
  image: node:20
  artifacts:
    paths:
      - build
  script:
    - |
      echo "********************************************"
      echo "Build details"
      echo "============================================"
      echo "Running build for ${ENV}"
      echo "********************************************"
    - npm ci
    - npm run build
  rules:
    - if: '($CI_PIPELINE_SOURCE == "schedule" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $TARGET_BRANCH || $CI_COMMIT_BRANCH == $TARGET_BRANCH)'
      when: on_success

build-staging:
  extends: .build
  variables:
    TARGET_BRANCH: develop

build-production:
  extends: .build
  before_script:
    - export ENV=PRODUCTION
  variables:
    TARGET_BRANCH: main
